name: Test and build

on:
  push:
    branches-ignore:
      - master

env:
  CI: true
jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 19]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        name: Setup node ${{ matrix.node }}
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Report coverage
        if: ${{ matrix.node == '18' }}
        uses: codecov/codecov-action@v3
