name: Test and build

on:
  push:
    branches-ignore:
      - master

env:
  CI: true
jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Report coverage
        uses: codecov/codecov-action@v3
